---

- name: Gathering facts
  hosts: all
  gather_facts: yes
  user: "{{ANSIBLE_USER}}"
  become: yes
  become_method: sudo


- name: Pre_requisites
  hosts: all
  user: "{{ANSIBLE_USER}}"
  become: yes
  become_method: sudo
  roles:
  - pre_requisites

- name: download and configure cdh parcel repo
  hosts: cloudera_master
  user: "{{ANSIBLE_USER}}"
  become: yes
  become_method: sudo
  roles:
  - parcel-repo

- name: Mysql
  hosts: mysql
  user: "{{ANSIBLE_USER}}"
  become: yes
  become_method: sudo
  roles:
  - mysql

- name: hadoop DBs
  hosts: mysql
  user: "{{ANSIBLE_USER}}"
  become: yes
  become_method: sudo
  roles:
  - hadoop-db

- name: synthesys DBs
  hosts: mysql
  user: "{{ANSIBLE_USER}}"
  become: yes
  become_method: sudo
  roles:
  - synthesys-db
