---
- name: create hadoop databases
  mysql_db:
    name: "{{ item }}"
    state: present
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_root_password }}"
  with_items:
    - synthesys_app
    - synthesys_audit

- name: create user and grant access
  mysql_user:
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ item }}"
    password: synthesys
    host: "%"
    state: present
    priv: "{{ item }}.*:ALL"
  with_items:
    - synthesys_app
    - synthesys_audit

- name: copy sql file on sql server
  copy:
    src: roles/synthesys-db/files/synthesysaudit.sql
    dest: /tmp/

- name: execute sql file to create synthesys audit tables
  mysql_db:
    login_user: synthesys_audit
    login_password: synthesys
    state: import
    name: synthesys_audit
    target: /tmp/synthesysaudit.sql
  run_once: true
  ignore_errors: yes
