---
#######################################################################
# This playbook will configure the cloudera repository .         #
#######################################################################

- name: Preparing repo of Cloudera manager for RedHat
  template:
    src: cloudera-redhat.repo.j2
    dest: /etc/yum.repos.d/cloudera.repo
  when: ansible_os_family == 'RedHat'


- name: clean all
  shell: yum clean all
  when: ansible_os_family == 'RedHat'

- name: repolist
  shell: yum repolist
  when: ansible_os_family == 'RedHat'





