---
################################################################################
# Configuring repository of operating system on which cluster will be deployed #
################################################################################
   
 - name: clean all
   shell: yum clean all
   when: ansible_os_family == 'RedHat'

 - name: repolist
   shell: yum repolist
   when: ansible_os_family == 'RedHat'

