---
- name: install python mysql module
  yum:
    name: MySQL-python
    state: present

- name: install mysql rpm repo
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present

- name: install mysql rpm
  yum:
    name: mysql-server
    state: present

- name: start mysql service
  service:
    name: mysqld
    state: started

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  notify: Restart MySQL

- name: Delete anonymous user
  mysql_user:
    name: ''
    host: localhost
    state: absent


- name: create user and grant access
  mysql_user:
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}" 
    password: "{{ mysql_root_password }}"
    host: "%"
    state: present
    priv: "*.*:ALL"


- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent

- name: remove old innodb log files
  file:
    path: '/var/lib/mysql/{{ item }}'
    state: absent
  with_items:
    - ib_logfile0
    - ib_logfile1

- name: update my.cnf with appropriate configuration
  template: 
    src: roles/mysql/templates/my.cnf.template
    dest: /etc/my.cnf
  notify: Restart MySQL 
