---
- name: install python mysql module
  yum:
    name: MySQL-python
    state: present

- name: install mysql rpm repo
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present

- name: install mysql rpm
  yum:
    name: mysql-server
    state: present

- name: start mysql service
  service:
    name: mysqld
    state: started

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  notify: Restart MySQL

- name: Delete anonymous user
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: root password is present
  mysql_user: name=root host={{item}} password={{mysql_root_password | mandatory}} state=present
  with_items:
    - '::1'
    - '127.0.0.1'
    - 'localhost'

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent


