---
- name: create hadoop databases
  mysql_db:
    name: "{{ item }}"
    state: present
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_root_password }}"
  with_items:
    - amon
    - rman
    - scm
    - oozie

- name: create user and grant access
  mysql_user:
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ item }}"
    password: "{{ item }}" 
    host: "%"
    state: present
    priv: "{{ item }}.*:ALL"
  with_items:
    - amon
    - rman
    - scm
    - oozie
