---
# vars file for mysql
mysql_user: "root"
mysql_root_password: "synthesys"
datadir: /var/lib/mysql
transaction-isolation: READ-COMMITTED
symbolic-links: 0

key_buffer_size: 32M
max_allowed_packet: 32M
thread_stack: 256K
thread_cache_size: 64
query_cache_limit: 8M
query_cache_size: 64M
query_cache_type: 1

max_connections: 550

server_id: 1

binlog_format: mixed

read_buffer_size: 2M
read_rnd_buffer_size: 16M
sort_buffer_size: 8M
join_buffer_size: 8M

innodb_file_per_table: 1
innodb_flush_log_at_trx_commit : 2
innodb_log_buffer_size: 64M
innodb_buffer_pool_size: 4G
innodb_thread_concurrency: 8
innodb_flush_method: O_DIRECT
innodb_log_file_size: 512M

sql_mode: STRICT_ALL_TABLES
