---
################################
# Starting firewall / iptables # 
################################
- name: Start firewalld
  service: name=firewalld state=started
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_hosts'] }}"


